services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py runserver  0.0.0.0:8000
        # gunicorn core.wsgi -b 0.0.0.0:8000 --log-file -
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    depends_on:
      - postgres
    environment:
      - JWT_KEY=qwerty
      - LEDENBASE_TOKEN=$LEDENBASE_TOKEN
      - LEDENBASE_URL=$LEDENBASE_URL
      - SECRET_KEY=$SECRET_KEY
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - DEBUG=True
      - LOCAL=$LOCAL
      - MOLLIE_API_KEY=$MOLLIE_API_KEY
      - open_update_url=hhtps://open-update.leden.nl