# Generated by Django 4.1 on 2023-03-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='master_stock',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='units',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='master_stock',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.FloatField(default=1),
        ),
    ]
