# Generated by Django 4.1 on 2023-03-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stock_product_historicalproduct_master_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default=' ', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
