# Generated by Django 4.1 on 2023-03-24 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmutations',
            name='units',
            field=models.CharField(choices=[('units', 'units'), ('liters', 'liters'), ('grams', 'grams'), ('meters', 'meters'), ('pieces', 'pieces'), ('bottles', 'bottles'), ('packs', 'packs'), ('bags', 'bags'), ('boxes', 'boxes')], default='units', max_length=10),
        ),
        migrations.CreateModel(
            name='HistoricalStockMutations',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('units', models.CharField(choices=[('units', 'units'), ('liters', 'liters'), ('grams', 'grams'), ('meters', 'meters'), ('pieces', 'pieces'), ('bottles', 'bottles'), ('packs', 'packs'), ('bags', 'bags'), ('boxes', 'boxes')], default='units', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, editable=False)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stock')),
            ],
            options={
                'verbose_name': 'historical stock mutations',
                'verbose_name_plural': 'historical stock mutationss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('quantity', models.FloatField()),
                ('units', models.CharField(choices=[('units', 'units'), ('liters', 'liters'), ('grams', 'grams'), ('meters', 'meters'), ('pieces', 'pieces'), ('bottles', 'bottles'), ('packs', 'packs'), ('bags', 'bags'), ('boxes', 'boxes')], default='units', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical stock',
                'verbose_name_plural': 'historical stocks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
