# Generated by Django 4.1 on 2023-03-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockmutations_units_historicalstockmutations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='grootboek_waarde',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='grootboek_waarde',
            field=models.TextField(blank=True, null=True),
        ),
    ]
