# Generated by Django 4.1 on 2023-05-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_historicalproduct_grootboek_waarde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
