# Generated by Django 4.1 on 2022-12-29 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='user',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, related_name='main_client_applications', to=settings.AUTH_USER_MODEL, verbose_name='client user'),
            preserve_default=False,
        ),
    ]
