# Generated by Django 4.0 on 2022-11-06 23:58

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personel', verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='buyer',
            field=models.ForeignKey(on_delete=models.SET(users.models.Holder), related_name='purchases', to='users.holder'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='orders',
            field=models.ManyToManyField(related_name='ordered', to='purchase.Order'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='seller',
            field=models.ForeignKey(on_delete=models.SET(users.models.Personel), related_name='sold', to='users.personel'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='cat_products', to='purchase.Product'),
        ),
        migrations.AddField(
            model_name='barcycle',
            name='closing_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing', to='purchase.report', verbose_name='closing_report'),
        ),
        migrations.AddField(
            model_name='barcycle',
            name='opening_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening', to='purchase.report', verbose_name='opening_report'),
        ),
    ]
