# Generated by Django 4.0.5 on 2022-06-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_rename_product_purchase_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
