# Generated by Django 4.0 on 2022-11-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
