# Generated by Django 4.0.5 on 2022-06-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchase_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='orders',
            field=models.ManyToManyField(related_name='ordered', to='purchase.order'),
        ),
    ]
