# Generated by Django 4.0 on 2022-11-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchase_cash_purchase_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Producten'},
        ),
    ]
