# Generated by Django 4.0.5 on 2022-06-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_order_purchase_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
    ]
