# Generated by Django 4.0 on 2022-11-23 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_card_options_alter_molliepayments_options_and_more'),
        ('purchase', '0005_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HapOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HapPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Happen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('cost', models.FloatField(default=0)),
                ('max_participants', models.IntegerField(default=0)),
                ('deducted_from', models.ManyToManyField(blank=True, related_name='payed_for', through='purchase.HapPayment', to='users.Holder')),
                ('participants', models.ManyToManyField(blank=True, related_name='ingeschreven_happen', through='purchase.HapOrder', to='users.Holder')),
            ],
            options={
                'verbose_name': 'Hap',
                'verbose_name_plural': 'Happen',
            },
        ),
        migrations.AddField(
            model_name='happayment',
            name='happen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.happen'),
        ),
        migrations.AddField(
            model_name='happayment',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.holder'),
        ),
        migrations.AddField(
            model_name='haporder',
            name='happen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.happen'),
        ),
        migrations.AddField(
            model_name='haporder',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.holder'),
        ),
    ]
