# Generated by Django 4.1 on 2022-09-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='cat_products', to='purchase.product'),
        ),
    ]
