# Generated by Django 4.1 on 2023-02-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_rename_payed_historicalpurchase_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name_plural': 'Producten'},
        ),
    ]
