# Generated by Django 4.0 on 2022-10-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Personel',
            new_name='personel',
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
