# Generated by Django 4.0 on 2022-10-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_barcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcycle',
            name='closing_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing', to='purchase.report', verbose_name='closing_report'),
        ),
        migrations.AddField(
            model_name='barcycle',
            name='opening_report',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opening', to='purchase.report', verbose_name='opening_report'),
            preserve_default=False,
        ),
    ]
