# Generated by Django 4.0 on 2022-10-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcycle',
            options={'ordering': ['-opening_report__date']},
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
