# Generated by Django 4.0 on 2022-10-21 12:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_alter_barcycle_options_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(default='#ffdd00', image_field=None, max_length=18, samples=None),
        ),
    ]
