# Generated by Django 4.0 on 2022-10-23 16:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_holder_user_alter_personel_user'),
        ('purchase', '0017_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='remaining_after_purchase',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='buyer',
            field=models.ForeignKey(on_delete=models.SET(users.models.Holder), related_name='purchases', to='users.holder'),
        ),
    ]
