# Generated by Django 4.0 on 2022-11-02 10:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_holder_user_alter_personel_user'),
        ('purchase', '0018_purchase_remaining_after_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='seller',
            field=models.ForeignKey(default=65, on_delete=models.SET(users.models.Personel), related_name='sold', to='users.personel'),
            preserve_default=False,
        ),
    ]
