# Generated by Django 4.0 on 2022-11-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_purchase_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='action',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Middle', 'Middle')], max_length=50, verbose_name='action'),
        ),
    ]
