# Generated by Django 4.0 on 2022-11-06 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.FloatField(default=0.0)),
                ('ledenbase_id', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, default='holder/user-default.jpg', null=True, upload_to='holder/')),
                ('image_ledenbase', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, default='personel/user-default.jpg', null=True, upload_to='personel/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='WalletUpgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('refund', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.holder')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personel')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50, unique=True)),
                ('card_name', models.CharField(max_length=15)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.holder')),
            ],
        ),
    ]
