# Generated by Django 4.1 on 2022-08-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='ledenbase_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
