# Generated by Django 4.1 on 2023-05-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonel',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='personel',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
