# Generated by Django 4.1 on 2022-09-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_personel'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='image',
            field=models.ImageField(blank=True, default='images/holder/user-default.png', null=True, upload_to='images/holder/'),
        ),
        migrations.AddField(
            model_name='personel',
            name='image',
            field=models.ImageField(blank=True, default='images/personel/user-default.png', null=True, upload_to='images/personel/'),
        ),
    ]
