# Generated by Django 4.0 on 2022-11-18 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_molliepayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='molliepayments',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
