# Generated by Django 4.1 on 2022-09-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_holder_image_personel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='image',
            field=models.ImageField(blank=True, default='holder/user-default.jpg', null=True, upload_to='holder/'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='image',
            field=models.ImageField(blank=True, default='personel/user-default.jpg', null=True, upload_to='personel/'),
        ),
    ]
