# Generated by Django 4.0 on 2022-11-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_walletupgrades_cash_walletupgrades_molliepayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletupgrades',
            name='molliePayment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='users.molliepayments'),
        ),
    ]
