# Generated by Django 4.0 on 2022-10-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_holder_image_alter_personel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='image_ledenbase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
