# Generated by Django 4.0 on 2022-11-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_walletupgrades_molliepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molliepayments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
