# Generated by Django 4.0 on 2022-11-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_holder_user_alter_personel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletUpgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('refund', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.holder')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personel')),
            ],
        ),
    ]
