# Generated by Django 4.0 on 2022-11-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_walletupgrades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50)),
                ('card_name', models.CharField(max_length=15)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.holder')),
            ],
        ),
    ]
