# Generated by Django 4.1 on 2023-02-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_historicalwalletupgrades_historicalpersonel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
